### ISSUE TITLE
Side menus for EN and RU

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#82]
Can you please add the main menus so I can finish building the content properly.
thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I added PL and RU now - teh side menues are also there, but need the correct path first to have them added.

**Comment by ursulafeu** [comment]
Thank you Andreas, two things please:
1) title "Hauptnavigation PL" is visible: http://viszerale-therapie.at/pl/kurse/opis-kursu
2) about the correct path - I can't find why it says 
http://viszerale-therapie.at/pl/**kurse**/opis-kursu
--> where can I change this to kursy?

**Comment by Andreas-Schoenefeldt** [comment]
I removed the pl title - the kursy has something to do with the URL patterns, I need to find this again, but not tonight ;)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I fixed now also the main menu layout and that it will work also in other languages for mobile. For PL I added the kursy domain path, so that the courses should now get properly generated urls. 

If teh url is correct, the course menu will be on the left side also visible. For teh otehrs, we need first to see how the url pathes are, so that we can configure them properly.

**Comment by ursulafeu** [comment]
Miejsca Kursów
O nas
Szkoleniu

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, the side menus are now there - do we have already a russian translation for:
* Kurse
* Seminarorte
* Über uns
* Ausbildung

**Comment by ursulafeu** [comment]
Thank you! Russian I have not started yet, so no idea at the moment. I will close this ticket for now and open a new one when we need it for Russian.
